### PR TITLE
Add ability to pass through transform plugins to browserify.

### LINKED ISSUE #55: Add option to allow transforms to be passed into browserify.

### PR DESCRIPTION
**Pull request by SteffanDonal**
Fixes #55

### CODE REVIEW

**Comment by philkunz** [comment]
awesome!
Did you test that it works?
Anyway, I have to write better tests for this module. :)

Another quick thought:  the "if block" starting in line 29 is already tested by "if block" starting in line 8?

**Comment by SteffanDonal** [comment]
Yup, tested and can confirm that it works! The intention of the first check is to turn the list of transforms into an array if only one is passed - though actually since you've drawn that to my attention I've spotted a bug with it. I'm gonna fix it and update.

**Comment by philkunz** [comment]
v2.1.0 has this PR included. Thanks so much for the great work!

**Comment by philkunz** [comment]
What link should I put in the README to state your contribution?

**Comment by philkunz** [comment]
See v2.1.1, I added your name with link to github in the Contributors section. If you want it changed, let me know. Cheers, and have a nice evening!

**Comment by sdaitzman** [comment]
How does one actually use the transforms? gulp-browser breaks on my code when I use arrow functions, so I'd like to use babel to process my ES6 source into ES5 before I browserify it.

**Comment by philkunz** [comment]
quick note: I'm transitioning to GitLab. Please reraise your issue here:
https://gitlab.com/pushrocks/gulp-browser/issues

this  repo will go into mirror mode and issues will be removed.

**Pull request merged**
